using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MouseLook : MonoBehaviour {

	public float lookSensitivity = 5;
	private float yRotation;
	private float xRotation;
	private float currentYRotation;
	private float currentXRotation;
	private float yRotationV = 0.0f;
	private float xRotationV = 0.0f;
	public float lookSmoothDamp = 0.1f;
	
	// Update is called once per frame
	void Update () {
		yRotation += Input.GetAxis("Mouse X") * lookSensitivity;
		xRotation -= Input.GetAxis("Mouse Y") * lookSensitivity;

		xRotation = Mathf.Clamp(xRotation, -90, 90);
		
		currentXRotation = Mathf.SmoothDamp(currentXRotation, xRotation, ref xRotationV, lookSmoothDamp);
		currentYRotation = Mathf.SmoothDamp(currentYRotation, yRotation, ref yRotationV, lookSmoothDamp);

		transform.rotation = Quaternion.Euler(currentXRotation, currentYRotation, 0);
	}
}
